HealthCare.MVC/Entities/Agent.cs
namespace HealthCare.MVC.Entities
{
    public partial class Agent
    {
        public Agent()
        {
            Asigns = new HashSet<Asign>();
        }

        public int Id { get; set; }
        public string Email { get; set; } = null!;
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string PhoneNumber { get; set; } = null!;
        public string Address { get; set; } = null!;
        public string Password { get; set; } = null!;
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Role { get; set; } = null!;

        public virtual ICollection<Asign> Asigns { get; set; }
    }
}

HealthCare.MVC/Controllers/AsignsController.cs
using AutoMapper;
using HealthCare.MVC.Entities;
using HealthCare.MVC.Models;
using HealthCare.MVC.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace HealthCare.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AsignsController : Controller
    {
        private readonly IAsignService _asignService;
        private readonly IAgentService _agentService;
        private readonly ICustomerService _customerService;
        private readonly IMapper _mapper;

        public AsignsController(IAsignService asignService, IMapper mapper, IAgentService agentService, ICustomerService customerService)
        {
            _asignService = asignService;
            _agentService = agentService;
            _customerService = customerService;
            _mapper = mapper;
        }

        // GET: Asigns
        public async Task<IActionResult> Index(string SearchString)
        {
            var healthCareContext = _asignService.GetAll().Include(a => a.Agent).Include(a => a.Customer);
            if (SearchString != null)
            {
                TempData["SearchString"] = SearchString;
                return View(healthCareContext.Where(x => x.Agent.Email.ToLower().Contains(SearchString.ToLower())
                || x.Customer.Email.ToLower().Contains(SearchString.ToLower()))
                    .ToList().OrderBy(u => u.Agent.Email == ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value ? 0 : 1)
                               .ThenBy(u => u.Agent.Email));
            }
            return View(healthCareContext.ToList().OrderBy(u => u.Agent.Email == ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value ? 0 : 1)
                               .ThenBy(u => u.Agent.Email));
        }

        // GET: Asigns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _asignService == null || id == 0)
            {
                return NotFound();
            }

            var asign = await _asignService.GetAll()
                .Include(a => a.Agent)
                .Include(a => a.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asign == null)
            {
                return NotFound();
            }

            return View(asign);
        }
        // GET: Asigns/Create
        public IActionResult Create(int id)
        {
            TempData["Active"] = "Agents";
            TempData["AgentId"] = id;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email");
            return View();
        }

        // POST: Asigns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AgentId,CustomerId")] AsignCreateModel asign)
        {
            if (ModelState.IsValid)
            {
                var checkList = _asignService.Get(x => x.AgentId == asign.AgentId && x.CustomerId == asign.CustomerId); 
                if (checkList.Any())
                {
                    if (checkList.Where(x => x.IsDeleted == true).Any())
                    {
                        var asignUpdate = checkList.Where(x => x.IsDeleted == true).FirstOrDefault();
                        asignUpdate.IsDeleted = false;
                        asignUpdate.UpdatedDate = DateTime.Now;
                        _asignService.Update(asignUpdate);
                        await _asignService.SaveChangeAsync();
                        return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
                    }
                    else
                    {
                        ModelState.AddModelError("CustomerId", "This customer is already assigned to this agent.");
                    }
                }
                else
                {
                    await _asignService.AddAsync(_mapper.Map<Asign>(asign));
                    await _asignService.SaveChangeAsync();
                    return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
                }
            }
            TempData["Active"] = "Agents";
            TempData["AgentId"] = asign.AgentId;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email", asign.CustomerId);
            return View(asign);
        }

        // GET: Asigns/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _asignService == null || id == 0)
            {
                return NotFound();
            }

            var asign = await _asignService.FindAsync(id);
            if (asign == null)
            {
                return NotFound();
            }
            TempData["Active"] = "Agents";
            TempData["AgentId"] = asign.AgentId;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email", asign.CustomerId);
            return View(_mapper.Map<AsignUpdateModel>(asign));
        }

        // POST: Asigns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AgentId,CustomerId")] AsignUpdateModel asign)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var checkList = _asignService.Get(x => x.AgentId == asign.AgentId && x.CustomerId == asign.CustomerId);
                    if (checkList.Any())
                    {
                        if (!checkList.Where(x => x.Id == id).Any())
                        {
                            ModelState.AddModelError("AgentId", "This customer is already assigned to this agent.");
                            ModelState.AddModelError("CustomerId", "This customer is already assigned to this agent.");
                        }
                    }
                    if (ModelState.ErrorCount == 0)
                    {
                        var asignUpdate = await _asignService.FindAsync(id);
                        asignUpdate.AgentId = asign.AgentId;
                        asignUpdate.CustomerId = asign.CustomerId;
                        asignUpdate.UpdatedDate = DateTime.Now;
                        _asignService.Update(asignUpdate);
                        await _asignService.SaveChangeAsync();
                        return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsignExists(asign.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            TempData["Active"] = "Agents";
            TempData["AgentId"] = asign.AgentId;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email", asign.CustomerId);
            return View(asign);
        }

        // GET: Asigns/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _asignService == null)
            {
                return NotFound();
            }

            var asign = await _asignService.GetAll()
                .Include(a => a.Agent)
                .Include(a => a.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asign == null)
            {
                return NotFound();
            }

            TempData["Active"] = "Agents";
            return View(asign);
        }

        // POST: Asigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_asignService == null)
            {
                return Problem("Entity set 'HealthCareContext.Asigns'  is null.");
            }
            var asign = await _asignService.FindAsync(id);
            asign.IsDeleted = true;
            asign.UpdatedDate = DateTime.Now;
            _asignService.Update(asign);

            await _asignService.SaveChangeAsync();
            return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
        }

        private bool AsignExists(int id)
        {
            return (_asignService.GetAll()?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HealthCare.MVC/Views/Agents/Create.cshtml
@model AgentCreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Agent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <select asp-for="Role" class="form-control" asp-items="ViewBag.Role"></select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HealthCare.MVC/Views/Agents/Delete.cshtml
@model AgentViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HealthCare.MVC/Views/Agents/Details.cshtml
@model AgentDetailsModel

@{
    ViewData["Title"] = "Agent Details";
}

<div class="container py-5">
    @* <h1 class="text-center mb-5">Details</h1> *@
    <div class="card shadow-lg">
        <div class="card-body">
            <h1 class="card-title text-center mb-4 " style="font-weight: bold;">Agent Details</h1>
            <hr />
            <dl class="row">
                <dt class="col-sm-3 text-end">Email:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Email)</dd>

                <dt class="col-sm-3 text-end">First Name:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.FirstName)</dd>

                <dt class="col-sm-3 text-end">Last Name:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.LastName)</dd>

                <dt class="col-sm-3 text-end">Phone Number:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.PhoneNumber)</dd>

                <dt class="col-sm-3 text-end">Address:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Address)</dd>

                <dt class="col-sm-3 text-end">Updated Date:</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.UpdatedDate)</dd>
            </dl>
        </div>
    </div>
    <div class="mt-5 d-flex ">
        @if (User.IsInRole("Admin"))
        {
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        }
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

<br />

<h3 style="text-align: center; font-weight: bold;">Asigned Customers</h3>
@if (User.IsInRole("Admin"))
{
    <a asp-action="Create" asp-controller="Asigns" asp-route-id="@Model.Id" class="btn btn-primary btn-sm">Add</a>
}

@if (Model.Asigns.Count() > 0)
{

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr class="text-center">
                <th>Email</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Asigns)
            {
                <tr class="text-center">
                    <td>@Html.DisplayFor(modelItem => item.Customer.Email)</td>
                    <td>@Html.DisplayFor(modelItem => item.Customer.FirstName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Customer.LastName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Customer.PhoneNumber)</td>
                    <td>@Html.DisplayFor(modelItem => item.Customer.Address)</td>
                    @if (User.IsInRole("Admin"))
                    {
                        <td class="text-center">
                            <a asp-action="Details" asp-controller="Customers" asp-route-id="@item.Customer.Id" class="btn btn-info btn-sm">Details</a>
                            <a asp-action="Edit" asp-controller="Asigns" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Edit</a>
                            <a asp-action="Delete" asp-controller="Asigns" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    }
                    else
                    {
                        <td class="text-center">
                            <a asp-action="Details" asp-controller="Customers" asp-route-id="@item.Customer.Id" class="btn btn-info btn-sm">Details</a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p style="text-align: center; font-weight: bold;">No customers asigned yet.</p>
}

HealthCare.MVC/Views/Agents/Edit.cshtml
@using HealthCare.MVC.Models
@model AgentUpdateModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Agent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <select asp-for="Role" class="form-control" asp-items="ViewBag.Role"></select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

HealthCare.MVC/Views/Agents/Index.cshtml
@model IEnumerable<AgentViewModel>

@{
    ViewData["Title"] = "Agents List";
}

@* <h1 style="text-align: center; font-weight: bold;">Agents</h1>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name:
            <input type="text" name="SearchString" valplaceholder="Search..." value="@TempData["SearchString"]" />
            <input type="submit" class="btn btn-primary" value="Search" />
        </p>
    </div>
</form> *@

<p>
    <a asp-action="Create" class="btn btn-primary btn-sm">Add Agent</a>
</p>
<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr class="text-center">
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                @if (User.IsInRole("Admin"))
                {
                    <td class="text-center">
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">Details</a> |
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                }
                else
                {
                    <td class="text-center">
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">Details</a>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>