HealthCare.MVC/Entities/Asign.cs
namespace HealthCare.MVC.Entities
{
    public partial class Asign
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int CustomerId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Agent Agent { get; set; } = null!;
        public virtual Customer Customer { get; set; } = null!;
    }
}

HealthCare.MVC/Controllers/AsignsController.cs
using AutoMapper;
using HealthCare.MVC.Entities;
using HealthCare.MVC.Models;
using HealthCare.MVC.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace HealthCare.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AsignsController : Controller
    {
        private readonly IAsignService _asignService;
        private readonly IAgentService _agentService;
        private readonly ICustomerService _customerService;
        private readonly IMapper _mapper;

        public AsignsController(IAsignService asignService, IMapper mapper, IAgentService agentService, ICustomerService customerService)
        {
            _asignService = asignService;
            _agentService = agentService;
            _customerService = customerService;
            _mapper = mapper;
        }

        // GET: Asigns
        public async Task<IActionResult> Index(string SearchString)
        {
            var healthCareContext = _asignService.GetAll().Include(a => a.Agent).Include(a => a.Customer);
            if (SearchString != null)
            {
                TempData["SearchString"] = SearchString;
                return View(healthCareContext.Where(x => x.Agent.Email.ToLower().Contains(SearchString.ToLower())
                || x.Customer.Email.ToLower().Contains(SearchString.ToLower()))
                    .ToList().OrderBy(u => u.Agent.Email == ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value ? 0 : 1)
                               .ThenBy(u => u.Agent.Email));
            }
            return View(healthCareContext.ToList().OrderBy(u => u.Agent.Email == ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value ? 0 : 1)
                               .ThenBy(u => u.Agent.Email));
        }

        // GET: Asigns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _asignService == null || id == 0)
            {
                return NotFound();
            }

            var asign = await _asignService.GetAll()
                .Include(a => a.Agent)
                .Include(a => a.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asign == null)
            {
                return NotFound();
            }

            return View(asign);
        }
        // GET: Asigns/Create
        public IActionResult Create(int id)
        {
            TempData["Active"] = "Agents";
            TempData["AgentId"] = id;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email");
            return View();
        }

        // POST: Asigns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AgentId,CustomerId")] AsignCreateModel asign)
        {
            if (ModelState.IsValid)
            {
                var checkList = _asignService.Get(x => x.AgentId == asign.AgentId && x.CustomerId == asign.CustomerId); 
                if (checkList.Any())
                {
                    if (checkList.Where(x => x.IsDeleted == true).Any())
                    {
                        var asignUpdate = checkList.Where(x => x.IsDeleted == true).FirstOrDefault();
                        asignUpdate.IsDeleted = false;
                        asignUpdate.UpdatedDate = DateTime.Now;
                        _asignService.Update(asignUpdate);
                        await _asignService.SaveChangeAsync();
                        return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
                    }
                    else
                    {
                        ModelState.AddModelError("CustomerId", "This customer is already assigned to this agent.");
                    }
                }
                else
                {
                    await _asignService.AddAsync(_mapper.Map<Asign>(asign));
                    await _asignService.SaveChangeAsync();
                    return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
                }
            }
            TempData["Active"] = "Agents";
            TempData["AgentId"] = asign.AgentId;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email", asign.CustomerId);
            return View(asign);
        }

        // GET: Asigns/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _asignService == null || id == 0)
            {
                return NotFound();
            }

            var asign = await _asignService.FindAsync(id);
            if (asign == null)
            {
                return NotFound();
            }
            TempData["Active"] = "Agents";
            TempData["AgentId"] = asign.AgentId;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email", asign.CustomerId);
            return View(_mapper.Map<AsignUpdateModel>(asign));
        }

        // POST: Asigns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AgentId,CustomerId")] AsignUpdateModel asign)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var checkList = _asignService.Get(x => x.AgentId == asign.AgentId && x.CustomerId == asign.CustomerId);
                    if (checkList.Any())
                    {
                        if (!checkList.Where(x => x.Id == id).Any())
                        {
                            ModelState.AddModelError("AgentId", "This customer is already assigned to this agent.");
                            ModelState.AddModelError("CustomerId", "This customer is already assigned to this agent.");
                        }
                    }
                    if (ModelState.ErrorCount == 0)
                    {
                        var asignUpdate = await _asignService.FindAsync(id);
                        asignUpdate.AgentId = asign.AgentId;
                        asignUpdate.CustomerId = asign.CustomerId;
                        asignUpdate.UpdatedDate = DateTime.Now;
                        _asignService.Update(asignUpdate);
                        await _asignService.SaveChangeAsync();
                        return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsignExists(asign.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            TempData["Active"] = "Agents";
            TempData["AgentId"] = asign.AgentId;
            ViewData["CustomerId"] = new SelectList(_customerService.GetAll(), "Id", "Email", asign.CustomerId);
            return View(asign);
        }

        // GET: Asigns/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _asignService == null)
            {
                return NotFound();
            }

            var asign = await _asignService.GetAll()
                .Include(a => a.Agent)
                .Include(a => a.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asign == null)
            {
                return NotFound();
            }

            TempData["Active"] = "Agents";
            return View(asign);
        }

        // POST: Asigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_asignService == null)
            {
                return Problem("Entity set 'HealthCareContext.Asigns'  is null.");
            }
            var asign = await _asignService.FindAsync(id);
            asign.IsDeleted = true;
            asign.UpdatedDate = DateTime.Now;
            _asignService.Update(asign);

            await _asignService.SaveChangeAsync();
            return RedirectToAction("Details", "Agents", new { id = asign.AgentId });
        }

        private bool AsignExists(int id)
        {
            return (_asignService.GetAll()?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HealthCare.MVC/Controllers/NotesController.cs
using AutoMapper;
using HealthCare.MVC.Entities;
using HealthCare.MVC.Models;
using HealthCare.MVC.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace HealthCare.MVC.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly INoteService _noteService;
        private readonly ICustomerService _asignService;
        private readonly IMapper _mapper;

        public NotesController(INoteService noteService, ICustomerService asignService, IMapper mapper)
        {
            _noteService = noteService;
            _asignService = asignService;
            _mapper = mapper;
        }

        // GET: Notes
        public async Task<IActionResult> Index(int asignId, string SearchString)
        {

            TempData["CustomerId"] = asignId;
            var check = _asignService.Get(x => x.Id == asignId).FirstOrDefault();
            //if(check.Agent.Email == ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value)
            //{
            //    TempData["Check"] = check;
            //}
            //else
            //{
            //    TempData["Check"] = check;
            //}
            if (SearchString != null)
            {
                TempData["SearchString"] = SearchString;
                var list = _noteService.Get(
                        x => x.CustomerId == asignId)
                        .Where(x => x.Title.ToLower().Contains(SearchString.ToLower())
                        || x.Content.Contains(SearchString.ToLower())
                        ).ToList();
                return View(list);
            }
            else
            {
                return View(_noteService.Get(x => x.CustomerId == asignId).ToList());
            }
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _noteService == null || id == 0)
            {
                return NotFound();
            }

            var note = await _noteService.GetAll()
                .Include(n => n.Customer)
                //.ThenInclude(a => a.Customer)
                //.Include(n => n.Customer).ThenInclude(a => a.Agent)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            TempData["CustomerId"] = note.CustomerId;
            TempData["Active"] = "Agents";
            return View(note);
        }

        public List<string> TypeList()
        {

            var enumValues = Enum.GetValues(typeof(NoteType));
            var typeList = new List<string>();
            foreach (var value in enumValues)
            {
                typeList.Add(value.ToString());
            }
            return typeList;
        }

        // GET: Notes/Create
        public IActionResult Create(int customerId)
        {
            ViewData["Type"] = new SelectList(TypeList());
            TempData["Active"] = "Agents";
            TempData["AgentId"] = ((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value;
            TempData["CustomerId"] = customerId;
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AgentId,CustomerId,Title,Content,Type")] NoteCreateModel note)
        {
            if (ModelState.IsValid)
            {
                await _noteService.AddAsync(_mapper.Map<Note>(note));
                await _noteService.SaveChangeAsync();
                return RedirectToAction("Details", "Customers", new { id = note.CustomerId });

            }
            ViewData["Type"] = new SelectList(TypeList(), note.Type);
            TempData["Active"] = "Agents";
            TempData["CustomerId"] = note.CustomerId;
            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int id, int asignId)
        {
            if (id == null || _noteService == null)
            {
                return NotFound();
            }

            var note = await _noteService.FindAsync(id);
            if (asignId == null || asignId == 0)
            {
                asignId = note.CustomerId;
            }
            if (note == null)
            {
                return NotFound();
            }
            ViewData["Type"] = new SelectList(TypeList(), note.Type);
            TempData["Active"] = "Agents";
            TempData["CustomerId"] = asignId;
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AgentId,CustomerId,Title,Content,Type,CreatedDate,UpdatedDate")] NoteUpdateModel note)
        {
            if (id != note.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    note.UpdatedDate = DateTime.Now;
                    _noteService.Update(_mapper.Map<Note>(note));
                    await _noteService.SaveChangeAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Customers", new { id = note.CustomerId });
            }
            ViewData["Type"] = new SelectList(TypeList(), note.Type);
            TempData["CustomerId"] = note.CustomerId;
            TempData["Active"] = "Agents";
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _noteService == null)
            {
                return NotFound();
            }

            var note = await _noteService.GetAll()
                .Include(n => n.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }
            TempData["CustomerId"] = note.CustomerId;
            TempData["Active"] = "Agents";
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_noteService == null)
            {
                return Problem("Entity set 'HealthCareContext.Notes'  is null.");
            }
            //var asignId = _noteService.Get(x => x.Id == id).FirstOrDefault().CustomerId;
            //await _noteService.Remove(id);
            var note = await _noteService.FindAsync(id);
            note.IsDeleted = true;
            note.UpdatedDate = DateTime.Now;
            _noteService.Update(note);
            await _noteService.SaveChangeAsync();
            return RedirectToAction("Details", "Customers", new { id = note.CustomerId });
        }

        private bool NoteExists(int id)
        {
            return (_noteService.GetAll()?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HealthCare.MVC/Views/Asigns/Create.cshtml
@model HealthCare.MVC.Models.AsignCreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Asign</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="AgentId" class="form-control" type="hidden" value="@TempData["AgentId"]" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

HealthCare.MVC/Views/Asigns/Delete.cshtml
@model HealthCare.MVC.Entities.Asign

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Asign</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agent.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HealthCare.MVC/Views/Asigns/Details.cshtml
@model HealthCare.MVC.Entities.Asign

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Asign</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agent.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HealthCare.MVC/Views/Asigns/Edit.cshtml
@model HealthCare.MVC.Models.AsignUpdateModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Asign</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input asp-for="AgentId" class="form-control" type="hidden" asp-items="@TempData["AgentId"]" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

HealthCare.MVC/Views/Asigns/Index.cshtml
@model IEnumerable<HealthCare.MVC.Entities.Asign>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by email:
            <input type="text" name="SearchString" valplaceholder="Search..." value="@TempData["SearchString"]" />
            <input type="submit" class="btn btn-primary" value="Search" />
        </p>
    </div>
</form>

<p>
    <a asp-action="Create" asp-route-asignId="@TempData["AsignId"]">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Agent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-area="" asp-controller="Agents" asp-action="Details" asp-route-id="@item.Agent.Id">@Html.DisplayFor(modelItem => item.Agent.Email)</a>
                </td>
                <td>
                    <a asp-area="" asp-controller="Customers" asp-action="Details" asp-route-id="@item.Customer.Id">@Html.DisplayFor(modelItem => item.Customer.Email)</a>
                </td>
                <td>
                    <a asp-action="Index" asp-controller="Notes" asp-route-asignId="@item.Id">Note List</a> |
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>